server:
  port: 2500

spring:
  application:
    name: spring-project-ticket-booking
  datasource:
    url: jdbc:mysql://localhost:3306/project-database?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
  data:
    redis:
      url: redis://localhost:6379

admin:
  password: Pratham57!?
  email: nimbalkarpratham2002@gmail.com